name: PlatformIO CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - controllino_maxi
          - front_garden
          - back_garden
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            .pio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-
            
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          
      - name: Build firmware
        run: pio run -e ${{ matrix.environment }}
        
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.environment }}
          path: |
            .pio/build/${{ matrix.environment }}/firmware.hex
            .pio/build/${{ matrix.environment }}/firmware.elf
          retention-days: 30
          
  check:
    name: Check Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            .pio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-
            
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          
      - name: Run static code analysis
        run: pio check --skip-packages
        continue-on-error: true
